services:
  kafka-broker-1:
    image: apache/kafka:latest
    container_name: kafka-broker-1
    pull_policy: missing
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://kafka-broker-1:29092,CONTROLLER://kafka-broker-1:33333,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:29092,EXTERNAL://localhost:9092

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker-1:33333,2@kafka-broker-2:33333,3@kafka-broker-3:33333

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  kafka-broker-2:
    image: apache/kafka:latest
    container_name: kafka-broker-2
    pull_policy: missing
    ports:
      - 9095:9095
      - 29095:29095
    depends_on:
      - kafka-broker-1
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://kafka-broker-2:29095,CONTROLLER://kafka-broker-2:33333, EXTERNAL://0.0.0.0:9095
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:29095,EXTERNAL://localhost:9095

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker-1:33333,2@kafka-broker-2:33333,3@kafka-broker-3:33333

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-broker-3:
    image: apache/kafka:latest
    container_name: kafka-broker-3
    pull_policy: missing
    ports:
      - 9096:9096
      - 29096:29096
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://kafka-broker-3:29096,CONTROLLER://kafka-broker-3:33333,EXTERNAL://0.0.0.0:9096
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-3:29096,EXTERNAL://localhost:9096

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker-1:33333,2@kafka-broker-2:33333,3@kafka-broker-3:33333

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    pull_policy: missing
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker-1:29092,kafka-broker-2:29095,kafka-broker-3:29096
      DYNAMIC_CONFIG_ENABLED: 'true'  